version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: springbootmongodb
    hostname: springbootmongodb
    ports:
      - "8085:8080"
    depends_on:
      - mongodb